// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:228636e1-82e6-4e8e-b170-a0198e6f3746",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_TMTjvrae3",
    "aws_user_pools_web_client_id": "6t0lbgk3nl42sbqe6mu347371v"
};


export default awsmobile;
